AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*
  RunRailsCops: true

Documentation:
  Exclude:
    - spec/**/*

TrailingBlankLines:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes
