AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*
  RunRailsCops: true

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes

TrailingBlankLines:
  Enabled: false
